// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using pathly_backend.Sessions.Infrastructure.Persistence;

#nullable disable

namespace pathly_backend.Sessions.Migrations
{
    [DbContext(typeof(SessionsDbContext))]
    [Migration("20250707234027_AddCancelReasonToSession")]
    partial class AddCancelReasonToSession
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("pathly_backend.Sessions.Domain.Entities.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("CancelReason")
                        .HasColumnType("text");

                    b.Property<DateTime>("EndsAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("PsychologistId")
                        .IsRequired()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("StartsAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("Sessions", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
